version: '2'

services:
  vault:
    image: vault:1.2.3
    command:
      - "vault"
      - "server"
      - "-dev"
      - "-dev-listen-address=0.0.0.0:8222"
      - "-dev-root-token-id=toor"
    ports:
    - 8222:8222
    cap_add:
      - IPC_LOCK
  kms:
    build: .
    command:
      - "-socketFile=/tmp/vault-kms.sock"
      - -transitPath=transit
      - -keyNames=auth
    environment:
      - VAULT_ADDR=http://vault:8222
      - VAULT_TOKEN=toor
