name: Docker
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: HurricanKai/Publish-Docker-Github-Action@master
      with:
        name: docker.pkg.github.com/gitirabassi/libvault/kms-plugin
        username: gitirabassi
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        snapshot: true
